format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

# meta:
#   bitrise.io:
#     machine_type_id: standard
#     stack: linux-docker-android-20.04

containers:
  golang:
    image: golang:1.22
services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    options: >-
      --health-cmd "redis-cli ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

workflows:
  # _clone:
  #   steps:
  #   - activate-ssh-key@4: { }
  #   - git-clone@8: {}
  #   - script:
  #       inputs:
  #       - content: go version

  test:
    envs:
    - REDIS_DSN: redis:6379
    steps:
    - script:
        inputs:
        - content: go version
    - with:
        container: golang
        services:
        - redis
        steps:
        - script:
            inputs:
            - content: docker ps -a
        - script:
            inputs:
            - content: go version
        - script:
            title: Run tests
            inputs:
            - content: go test ./...
