format_version: "15"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

containers:
  golang:
    image: golang:1.22

services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    options: >-
      --health-cmd "redis-cli ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

step_bundles:
  print_go_version:
    steps:
    - script:
        inputs:
        - content: go version

workflows:
  test:
    envs:
    - REDIS_DSN: redis:6379
    steps:
    - bundle::print_go_version: {}
    - with:
        container: golang
        services:
        - redis
        steps:
        - script:
            inputs:
            - content: go version
        - script:
            title: Run tests
            inputs:
            - content: go test ./...
    - script:
        inputs:
        - content: docker ps -a
