format_version: "15"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

containers:
  golang:
    image: golang:1.22

services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    options: >-
      --health-cmd "redis-cli ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

step_bundles:
  setup_repo:
    steps:
    - activate-ssh-key@4: { }
    - git-clone@8: { }

workflows:
  test:
    envs:
    - REDIS_DSN: redis:6379
    steps:
    - bundle::setup_repo: { }
    - with:
        container: golang
        services:
        - redis
        steps:
        - script@1:
            title: Run tests
            inputs:
            - content: go test ./...

  deploy:
    steps:
    - bundle::setup_repo: { }
    - with:
        container: golang
        steps:
        - script@1:
            title: Build
            inputs:
            - content: go build -o $BITRISE_DEPLOY_DIR/
    - deploy-to-bitrise-io@2: { }

meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
