containers:
  golang:
    image: golang:1.22

services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    options: >-
      --health-cmd "redis-cli ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5